### ISSUE TITLE
Я лучше нарисую 

### ISSUE THREAD

**Issue by Edrick53** [kubikvest/front#13]
0 экран
![screenshot_19](https://cloud.githubusercontent.com/assets/21133613/18246500/ad3c1f18-7374-11e6-9781-0aed0f2b0611.jpg)
- [ ] 1.1. Вместо "кубик уличный квест" - название квеста "Окольный град” (у нас же куча квестов будет) kubikvest/front#16
- [ ] 1.2. кстати, отсюда на титульной странице http://kubikvest.xyz есть только кнопка "играть", а будет 10 квестов? должен быть выбор квестов и еще видимо промежуточная страница с выбором картинками и описанием или вниз этой слайд. Лучше сразу заложить эту вариативность. kubikvest/front#15
- [ ] 1.3. Под названием квеста надо просто текстовое поле, обозначь его, к примеру "бла бла бла" потом я допишу. Там будет описание квеста, условия возрастные и тд. kubikvest/front#17
- [ ] 1.4. Далее куда надо подойти - это либо текстом прописать, либо унифицировать поле. 
- [ ] 1.5.  Важнее тут, чтобы если не туда подошел человек появился текст "Вы еще не на нужном месте, дойдите и еще раз нажмите кнопку "я на месте"". тексты мы потом отрулим еще не раз главное чтобы были поля и появлялись в нудное время.
- [x] 1.6. Таймеров тут никаких нет, единственное действие перенаправление кнопкой я на месте на следующий экран задания, там уже пойдет таймер частный и таймер общий.

экран задания
![screenshot_20](https://cloud.githubusercontent.com/assets/21133613/18246558/0252a53a-7375-11e6-9138-75f4cc17f360.jpg)
- [ ] 2.1. В экране задания, первого или какого либо нет шапки "задание 1". Человек же должен видеть это первое задание это второе, ориентироваться.
- [ ] 2.2. Кнопка называется отныне "проверить ответ", а не "я на месте" отсюда опять же два выхода: да или нет. да - новое задание, нет - "вы ошиблись подумайте еще и проверьте ответ снова" kubikvest/front#14
- [ ] 2.3. Внизу над таймером текст "Время до первой подсказки" иначе непонятно зачем тут таймер. kubikvest/front#18
- [x] 2.4. Кончается таймер появляется первая подсказка
- [ ] 2.5. Опять от первой подсказки идет таймер с текстом "время до второй подсказки" 
- [x] 2.6. Кончается появляется вторая подсказка
- [ ] 2.7. Идет таймер с текстом "время до ответа"
- [ ] 2.8. Появляется ответ "Туда сюда.  (Подойдите к этому объекту и пришлите свою геопозицию, чтобы получить следующее задание.)" и ваще целевые действия надо везде приписать, для тех кто не читает правила.
- [x] 2.9. На скрине я вижу ответ виден сразу, чего не должно быть естественно.
