### ISSUE TITLE
Подсказки для задания

### ISSUE THREAD

**Issue by iMega** [kubikvest/front#7]
# Проблема

В ходе игры у участником могут появиться затруднения с решением загаданного местоположения и переходом к следующему как требует игровой процесс.
# Решение

Необходимо отобразить подсказку после 20 минут с начала получения очередного задания. С тем же интервалом, с момента отображения первой подсказки, выдать вторую. Через 20 минут после второй подсказки показать ответ.
- [x] Добавить временную метку начала задания kubikvest/api#14
- [x] Добавить 2 поля под текст для подсказок kubikvest/api#15
- [x] Добавить правильный ответ (будет являться подсказкой) 
- [x] Добавить элемент для отображения текстов подсказки или ответа
- [ ] Макет для элемента для отображения текстов подсказки или ответа
- [x] Добавить таймер с вызовом метода получения подсказки kubikvest/front#9
- [ ] Макет для таймера с вызовом метода получения подсказки
